title: SPOT Research Group
email: soney@umich.edu
description: Human-centered research on programming tools and practices.
baseurl: ""
url: "https://from.so"

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty
plugins:
  - jekyll-feed

collections:
  papers:
    output: true
    permalink: /papers/:name/
  people_pages:
    output: true
    permalink: /people/:name/

exclude:
  - node_modules
  - public
  - src
  - strapi-export
  - strapi-export-conversion
  - gatsby-config.js
  - gatsby-node.js
  - package.json
  - yarn.lock
  - tsconfig.json
  - tslint.json
  - redeploy_listener.js
